### ISSUE TITLE
choose a subdomain

### ISSUE THREAD

**Issue by mattbailey0** [ombegov/policy-v2#6]
This site will live at a subdomain of cio.gov. Which one is most appropriate?  Options that have been suggested include management.cio.gov and policy.cio.gov.

**Comment by Thomas-Romanoff** [comment]
I would go with Policy.CIO.Gov since it matches the content of the site.

**Comment by mattbailey0** [comment]
@Thomas-Romanoff but then what about the other site we're building?

**Comment by Thomas-Romanoff** [comment]
I thought that was going to be Policy.gov or posibly Requirments.gov.  Is poilcy.cio.gov and management.cio.gov the only options we have under the cio domain?

**Comment by mattbailey0** [comment]
^^ extremely notional and way down the line.  And no, those two subdomains are not the only options!

**Comment by zenpuppet** [comment]
I would also lean towards policy.cio.gov. 
I believe as a user, I would expect to find a list of policies at policy.cio.gov. 
I would not expect to find policies at management.cio.gov.
However, management.cio.gov might translate to policies for certain types of users.

**Comment by Thomas-Romanoff** [comment]
Policy.CIO still resonates with me since the user will be expecting to see policies on the site.  We could get more specific by saying ITPolicies.CIO.Gov but that seems unnecessary.  There is also the call to action we expect users to engage.  They are going there to comment on draft policy.  If you want to work that in here are some ideas:
EngageIT.CIO
DigitalPolciy.CIO
OpenPolicy.CIO
CitizenIT.CIO
ProofPolicy.CIO
MarkUp.CIO
PolicyVoice.CIO

Just spit balling here

**Comment by konklone** [comment]
IMO, policy.cio.gov is a clear, reasonable subdomain.

**Comment by mattbailey0** [comment]
policy.cio.gov it is!
